#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BackgroundStreamingAudio.Resource", IsApplication=true)]

namespace BackgroundStreamingAudio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int album_art = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_card = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_av_fast_forward = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_av_next = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_av_pause = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_av_play = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_av_previous = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_av_repeat = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_av_rewind = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_av_shuffle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_av_stop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_launcher = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_stat_av_play_over_video = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int musicbytext = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int pauseButton = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int playButton = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int stopButton = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int mp3_url = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int pause = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int play = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int stop = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int BaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
